query GetTransactions($limit: Int! $skip: Int) {
    transactions(limit: $limit, skip: $skip) {
        total_rows
        data {
            id
            user {
                id
                first_name
                last_name
            }
            description
            merchant {
                id
                name
            }
            company_id
            debit
            credit
            amount
        }
    }
}
